// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class 123Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 1() {
    driver.get("https://classroom.google.com/r/MTg0ODM1NTQyODJa/sort-last-name/");
    driver.manage().window().setSize(new Dimension(1296, 1000));
    driver.findElement(By.cssSelector(".gb_jf > .gb_2b")).click();
    driver.findElement(By.linkText("Ещё")).click();
    driver.findElement(By.cssSelector("#gb265 > .gb_k")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
  @Test
  public void 2() {
    driver.get("https://classroom.google.com/h");
    driver.manage().window().setSize(new Dimension(698, 692));
    {
      WebElement element = driver.findElement(By.cssSelector(".DShyMc-MTg0ODM1NTQyODJa .R4EiSb > .onkcGd"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".gHz6xd:nth-child(1) .onkcGd > .YVvGBb:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.linkText("Лента"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Пользователи")).click();
    driver.close();
  }
  @Test
  public void 3() {
    driver.get("https://classroom.google.com/r/MTg0ODM1NTQyODJa/sort-last-name");
    driver.manage().window().setSize(new Dimension(698, 692));
    driver.findElement(By.linkText("Лента")).click();
    {
      WebElement element = driver.findElement(By.linkText("Задания"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
  @Test
  public void 4() {
    driver.get("https://classroom.google.com/r/MTg0ODM1NTQyODJa/sort-last-name");
    driver.manage().window().setSize(new Dimension(1296, 1000));
    driver.findElement(By.cssSelector(".oOGT6")).click();
    driver.findElement(By.cssSelector(".aerrld")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".DShyMc-MTg0ODM1NTQyODJa .R4EiSb > .onkcGd"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".gHz6xd:nth-child(2) .onkcGd > .YVvGBb:nth-child(1)")).click();
    driver.close();
  }
  @Test
  public void 5() {
    driver.get("https://accounts.google.com/signin/v2/sl/pwd?service=classroom&passive=1209600&continue=https%3A%2F%2Fclassroom.google.com%2Fr%2FMTg0ODM1NTQyODJa%2Fsort-last-name&followup=https%3A%2F%2Fclassroom.google.com%2Fr%2FMTg0ODM1NTQyODJa%2Fsort-last-name&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
    driver.manage().window().setSize(new Dimension(698, 692));
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector("#passwordNext > .ZFr60d")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#gbwa .gb_x"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
